name: Deploy Lambda Function

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start timer
        id: start_timer
        run: |
          echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@v3

      - name: Install zip tool
        run: sudo apt-get install zip -y

      - name: Create Zip file for Lambda function
        run: zip -r code.zip .

      - name: Update Lambda Function Code
        uses: aws-actions/aws-cli@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ca-central-1"
          cmd: |
            lambda update-function-code \
              --function-name arn:aws:lambda:ca-central-1:654654208693:function:testfunction \
              --zip-file fileb://code.zip

      - name: Stop timer and calculate duration
        id: stop_timer
        run: |
          BUILD_END_TIME=$(date +%s)
          BUILD_START_TIME=${{ steps.start_timer.outputs.start_time }}
          BUILD_DURATION=$((BUILD_END_TIME - BUILD_START_TIME))
          echo "Build duration: $BUILD_DURATION seconds"
          echo "build_duration=$BUILD_DURATION" >> $GITHUB_OUTPUT
        shell: bash

      - name: Send build duration to Dynatrace
        run: |
          echo "Sending build duration: ${{ steps.stop_timer.outputs.build_duration }} seconds"
          curl -X POST "${{ secrets.DYNATRACE_URL }}/api/v2/metrics/ingest" \
            -H "Content-Type: text/plain" \
            -H "Authorization: Api-Token ${{ secrets.DYNATRACE_API_TOKEN }}" \
            --data-raw "github.build.duration,build_time=seconds ${{ steps.stop_timer.outputs.build_duration }}"
