name: Deploy Lambda Function

env:
  datatype: "text/plain"

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start timer
        id: start_timer
        run: echo "start_time=$(date +%s)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/checkout@v2
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create Zip file for Lambda function
        run: zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
          args: "lambda update-function-code \
            --function-name arn:aws:lambda:ca-central-1:654654208693:function:testfunction \
            --zip-file fileb://code.zip"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "ca-central-1"

      - name: Stop timer and calculate duration
        id: stop_timer
        run: |
          BUILD_END_TIME=$(date +%s)
          BUILD_START_TIME=${{ steps.start_timer.outputs.start_time }}
          BUILD_DURATION=$((BUILD_END_TIME - BUILD_START_TIME))
          echo "BUILD_DURATION=$BUILD_DURATION" >> $GITHUB_ENV
          echo "Build duration: $BUILD_DURATION seconds"
        env:
         BUILD_DURATION: $BUILD_DURATION
        shell: bash

      - name: Send build duration to Dynatrace
        run: |
          curl -X POST "${{ vars.DYNATRACE_URL }}/api/v2/metrics/ingest" \
            -H "Content-Type: ${{env.datatype}}" \
            -H "Authorization: Api-Token ${{ secrets.DYNATRACE_API_TOKEN }}" \
            --data-raw "github.build.metric,duration=seconds $BUILD_DURATION"
        shell: bash
